#!/usr/bin/env python3
'''hwd
  Print "${PWD}" or "${HOST}:${PWD}" and copy it to the clipboard.

Usage:
  hwd [options]

Options:
  -h, --host      Include host.
  -q, --quote     Put single quotation marks around the path.
  -c, --copy      Print and copy path.
      --help      Show help.
      --version   Show version.

(c - MIT) T.W.J. de Geus | tom@geus.me | www.geus.me
'''

# ==================================================================================================

import os, docopt, socket

# parse command-line options
args = docopt.docopt(__doc__,version='0.0.1')

# initialize output
out = ''

# add host-name
if args['--host']: out += socket.gethostname() + ":"

# add path
if args['--quote']: out += "'" + os.environ['PWD'] + "'"
else              : out +=       os.environ['PWD']

# print output
print(out)

# copy
if args['--copy']:

  import pyperclip

  pyperclip.copy(out)
