#!/usr/bin/env python3
'''hwd
  Print "${HOST}:${PWD}" and copy it to the clipboard.

Usage:
  hwd

  -q, --quote     Put single quotation marks around the path.
  -h, --help      Show help.
      --version   Show version.

(c - MIT) T.W.J. de Geus | tom@geus.me | www.geus.me
'''

# ==================================================================================================

import os, docopt, socket

# parse command-line options
args = docopt.docopt(__doc__,version='0.0.1')

# set output
if args['--quote']: print(socket.gethostname() + ":'" + os.environ['PWD'] + "'")
else              : print(socket.gethostname() + ":"  + os.environ['PWD']      )



