#!/usr/bin/env python3
"""rm_regex
  Remove files using regular expressions. The program will prompt the user for
  confirmation before removing (unless the "--force" options is used).

Usage:
  rm_regex [options] <search> <files>...

Arguments:
  <search>    Regular expression to search.
  <files>     List of files on which to do the replacement.

Options:
  -h --help   Show help.
  --version   Show version.
  -f --force  Force move, don't prompt for user interaction.

Example:
  rm_regex "(.*)(_raw.svg)" *.svg

Copyright:
  T.W.J. de Geus
  tom@geus.me
  www.geus.me
"""

import sys, os, re, docopt

args = docopt.docopt(__doc__,version='0.1.1')

# ==================================================================================================

def confirm(message='Proceed [y/n]?\n'):
  while True:
    user = input(message)
    if not user                     : print('Please enter y or n.'); continue
    if user not in ['y','Y','n','N']: print('Please enter y or n.'); continue
    if user     in ['y','Y'        ]: return True
    if user     in ['n','N'        ]: return False

# ==================================================================================================

# check if all input files actually exist
for file in args['<files>']:
  if not os.path.isfile(file) and not os.path.isdir(file):
    print('Input {1:s} does not exist'.format(file))
    sys.exit(1)

# only keep input files that match the input regular-expression
args['<files>'] = [file for file in args['<files>'] if re.match(args['<search>'],file)]

# no files remaining -> quit
if len(args['<files>']) == 0:
  sys.exit(0)

# prompt the user for confirmation
if not args['--force']:

  # - construct print-format to align output
  w   = max([len(file) for file in args['<files>']])
  fmt = 'rm {file:'+str(w)+'s}'

  # - print all files
  for file in zip(args['<files>']):
    print(fmt.format(file=file))

  # - prompt user
  if not confirm():
    sys.exit(1)

# proceed with the renaming of all files
for file in zip(args['<files>']):
  os.remove(file,new)

